set search_path = wonks_ru;

CREATE ROLE Админ;
CREATE ROLE Модератор;
CREATE ROLE Пользователь;
CREATE ROLE Гость;

REVOKE EXECUTE ON FUNCTION wonks_ru.get_article_comments_paginated_filtered(INTEGER, INTEGER, TEXT, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_user_subscriptions_paginated_filtered(INTEGER, INTEGER, INTEGER, INTEGER, TEXT, TEXT, BOOLEAN) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_reports_paginated_filtered(INTEGER, INTEGER, TEXT, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.register_user(VARCHAR, VARCHAR, TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.update_article_status(INTEGER, INTEGER, wonks_ru.article_status) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.process_report(INTEGER, INTEGER, wonks_ru.complaint_status) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_user_notifications_paginated_filtered(INTEGER, INTEGER, INTEGER, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.unsubscribe_from_user(INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.set_subscription_notices(INTEGER, INTEGER, BOOLEAN) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.delete_comment(INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.remove_from_favourites(INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.edit_comment(INTEGER, INTEGER, TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.remove_article_rating(INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.create_article(INTEGER, VARCHAR, TEXT, TEXT, TEXT, INTEGER, wonks_ru.article_status, VARCHAR, TEXT[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.update_article(INTEGER, INTEGER, VARCHAR, TEXT, TEXT, TEXT, VARCHAR, INTEGER, wonks_ru.article_status, TEXT[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.report_user(INTEGER, INTEGER, TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_articles_paginated_filtered(INTEGER, INTEGER, INTEGER, TEXT, TEXT, TEXT, TEXT[], TIMESTAMPTZ, TIMESTAMPTZ) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_user_favourite_articles_paginated_filtered(INTEGER, INTEGER, INTEGER, TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.authenticate_user(TEXT, TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.subscribe_to_user(INTEGER, INTEGER, BOOLEAN) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.add_comment(INTEGER, INTEGER, TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.add_to_favourites(INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.set_article_rating(INTEGER, INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.delete_article(INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.delete_notification(INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.update_user_profile(INTEGER, VARCHAR, VARCHAR, VARCHAR) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.delete_all_user_notifications(INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.set_user_status(INTEGER, INTEGER, wonks_ru.user_status) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.create_category(INTEGER, VARCHAR) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.update_category(INTEGER, INTEGER, VARCHAR) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.delete_category(INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.create_tag(INTEGER, VARCHAR) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.update_tag(INTEGER, INTEGER, VARCHAR) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.delete_tag(INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.set_user_role(INTEGER, INTEGER, VARCHAR) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_article_details(TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_user_profile(INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.delete_user_account(INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.change_user_password(INTEGER, TEXT, TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.mark_notification_read(INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.mark_all_notifications_read(INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_dashboard_stats() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.export_schema_to_jsonb(TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.import_schema_from_jsonb(JSONB, TEXT, TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.export_schema_to_json_file(TEXT, TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.import_schema_from_json_file(TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_unread_notification_count(INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_category_list() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_tag_list() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_category_by_name(TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_tag_by_name(TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.check_user_favourite(INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.check_user_rating(INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.check_user_subscription(INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_articles_by_category(INTEGER, INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_articles_by_tag(INTEGER, INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_articles_by_author(INTEGER, INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_articles_by_status(wonks_ru.article_status, INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_user_feed(INTEGER, INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_trending_articles(INTERVAL, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_user_subscriptions(INTEGER, INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_user_followers(INTEGER, INTEGER, INTEGER) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION wonks_ru.get_user_comments(INTEGER, INTEGER, INTEGER) FROM PUBLIC;

-- Отзыв прав на таблицы/последовательности
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA wonks_ru FROM Гость;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA wonks_ru FROM Гость;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA wonks_ru FROM Пользователь;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA wonks_ru FROM Пользователь;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA wonks_ru FROM Модератор;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA wonks_ru FROM Модератор;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA wonks_ru FROM Админ;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA wonks_ru FROM Админ;

-- === Права на схему ===
GRANT USAGE ON SCHEMA wonks_ru TO Админ, Модератор, Пользователь, Гость;

-- === 1. Роль: Гость ===
GRANT EXECUTE ON FUNCTION wonks_ru.register_user(VARCHAR, VARCHAR, TEXT) TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.authenticate_user(TEXT, TEXT) TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_paginated_filtered(INTEGER, INTEGER, INTEGER, TEXT, TEXT, TEXT, TEXT[], TIMESTAMPTZ, TIMESTAMPTZ) TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_article_comments_paginated_filtered(INTEGER, INTEGER, TEXT, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_subscriptions_paginated_filtered(INTEGER, INTEGER, INTEGER, INTEGER, TEXT, TEXT, BOOLEAN) TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_article_details(TEXT) TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_profile(INTEGER) TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_category_list() TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_tag_list() TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_category_by_name(TEXT) TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_tag_by_name(TEXT) TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_by_category(INTEGER, INTEGER, INTEGER) TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_by_tag(INTEGER, INTEGER, INTEGER) TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_by_author(INTEGER, INTEGER, INTEGER) TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_trending_articles(INTERVAL, INTEGER) TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_subscriptions(INTEGER, INTEGER, INTEGER) TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_followers(INTEGER, INTEGER, INTEGER) TO Гость;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_comments(INTEGER, INTEGER, INTEGER) TO Гость;

-- === 2. Роль: Пользователь ===
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_paginated_filtered(INTEGER, INTEGER, INTEGER, TEXT, TEXT, TEXT, TEXT[], TIMESTAMPTZ, TIMESTAMPTZ) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_article_comments_paginated_filtered(INTEGER, INTEGER, TEXT, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_subscriptions_paginated_filtered(INTEGER, INTEGER, INTEGER, INTEGER, TEXT, TEXT, BOOLEAN) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.update_user_profile(INTEGER, VARCHAR, VARCHAR, VARCHAR) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.create_article(INTEGER, VARCHAR, TEXT, TEXT, TEXT, INTEGER, wonks_ru.article_status, VARCHAR, TEXT[]) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.update_article(INTEGER, INTEGER, VARCHAR, TEXT, TEXT, TEXT, VARCHAR, INTEGER, wonks_ru.article_status, TEXT[]) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_article(INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.add_comment(INTEGER, INTEGER, TEXT) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.edit_comment(INTEGER, INTEGER, TEXT) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_comment(INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.add_to_favourites(INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.remove_from_favourites(INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.set_article_rating(INTEGER, INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.remove_article_rating(INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.subscribe_to_user(INTEGER, INTEGER, BOOLEAN) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.unsubscribe_from_user(INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.set_subscription_notices(INTEGER, INTEGER, BOOLEAN) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.report_user(INTEGER, INTEGER, TEXT) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_notification(INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_all_user_notifications(INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_favourite_articles_paginated_filtered(INTEGER, INTEGER, INTEGER, TEXT, TEXT, TEXT) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_notifications_paginated_filtered(INTEGER, INTEGER, INTEGER, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_article_details(TEXT) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_profile(INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.change_user_password(INTEGER, TEXT, TEXT) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.mark_notification_read(INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.mark_all_notifications_read(INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_unread_notification_count(INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_category_list() TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_tag_list() TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_category_by_name(TEXT) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_tag_by_name(TEXT) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.check_user_favourite(INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.check_user_rating(INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.check_user_subscription(INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_by_category(INTEGER, INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_by_tag(INTEGER, INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_by_author(INTEGER, INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_feed(INTEGER, INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_trending_articles(INTERVAL, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_subscriptions(INTEGER, INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_followers(INTEGER, INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_comments(INTEGER, INTEGER, INTEGER) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.register_user(VARCHAR, VARCHAR, TEXT) TO Пользователь;
GRANT EXECUTE ON FUNCTION wonks_ru.authenticate_user(TEXT, TEXT) TO Пользователь;

-- === 3. Роль: Модератор ===
-- Наследует права Пользователя (если вы настроите ROLE HIERARCHY, иначе нужно копировать)
-- Копируем все права Пользователя:
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_paginated_filtered(INTEGER, INTEGER, INTEGER, TEXT, TEXT, TEXT, TEXT[], TIMESTAMPTZ, TIMESTAMPTZ) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_article_comments_paginated_filtered(INTEGER, INTEGER, TEXT, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_subscriptions_paginated_filtered(INTEGER, INTEGER, INTEGER, INTEGER, TEXT, TEXT, BOOLEAN) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.update_user_profile(INTEGER, VARCHAR, VARCHAR, VARCHAR) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.create_article(INTEGER, VARCHAR, TEXT, TEXT, TEXT, INTEGER, wonks_ru.article_status, VARCHAR, TEXT[]) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.update_article(INTEGER, INTEGER, VARCHAR, TEXT, TEXT, TEXT, VARCHAR, INTEGER, wonks_ru.article_status, TEXT[]) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_article(INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.add_comment(INTEGER, INTEGER, TEXT) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.edit_comment(INTEGER, INTEGER, TEXT) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_comment(INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.add_to_favourites(INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.remove_from_favourites(INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.set_article_rating(INTEGER, INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.remove_article_rating(INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.subscribe_to_user(INTEGER, INTEGER, BOOLEAN) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.unsubscribe_from_user(INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.set_subscription_notices(INTEGER, INTEGER, BOOLEAN) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.report_user(INTEGER, INTEGER, TEXT) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_notification(INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_all_user_notifications(INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_favourite_articles_paginated_filtered(INTEGER, INTEGER, INTEGER, TEXT, TEXT, TEXT) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_notifications_paginated_filtered(INTEGER, INTEGER, INTEGER, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_article_details(TEXT) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_profile(INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.change_user_password(INTEGER, TEXT, TEXT) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.mark_notification_read(INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.mark_all_notifications_read(INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_unread_notification_count(INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_category_list() TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_tag_list() TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_category_by_name(TEXT) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_tag_by_name(TEXT) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.check_user_favourite(INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.check_user_rating(INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.check_user_subscription(INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_by_category(INTEGER, INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_by_tag(INTEGER, INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_by_author(INTEGER, INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_feed(INTEGER, INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_trending_articles(INTERVAL, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_subscriptions(INTEGER, INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_followers(INTEGER, INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_comments(INTEGER, INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.register_user(VARCHAR, VARCHAR, TEXT) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.authenticate_user(TEXT, TEXT) TO Модератор;
-- Дополнительные права Модератора:
GRANT EXECUTE ON FUNCTION wonks_ru.update_article_status(INTEGER, INTEGER, wonks_ru.article_status) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.create_tag(INTEGER, VARCHAR) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.update_tag(INTEGER, INTEGER, VARCHAR) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_tag(INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.create_category(INTEGER, VARCHAR) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.update_category(INTEGER, INTEGER, VARCHAR) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_category(INTEGER, INTEGER) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.process_report(INTEGER, INTEGER, wonks_ru.complaint_status) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_reports_paginated_filtered(INTEGER, INTEGER, TEXT, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.set_user_status(INTEGER, INTEGER, wonks_ru.user_status) TO Модератор;
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_by_status(wonks_ru.article_status, INTEGER, INTEGER) TO Модератор;

-- === 4. Роль: Админ ===
-- Наследует права Модератора (если вы настроите ROLE HIERARCHY, иначе нужно копировать)
-- Копируем все права Модератора:
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_paginated_filtered(INTEGER, INTEGER, INTEGER, TEXT, TEXT, TEXT, TEXT[], TIMESTAMPTZ, TIMESTAMPTZ) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_article_comments_paginated_filtered(INTEGER, INTEGER, TEXT, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_subscriptions_paginated_filtered(INTEGER, INTEGER, INTEGER, INTEGER, TEXT, TEXT, BOOLEAN) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.update_user_profile(INTEGER, VARCHAR, VARCHAR, VARCHAR) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.create_article(INTEGER, VARCHAR, TEXT, TEXT, TEXT, INTEGER, wonks_ru.article_status, VARCHAR, TEXT[]) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.update_article(INTEGER, INTEGER, VARCHAR, TEXT, TEXT, TEXT, VARCHAR, INTEGER, wonks_ru.article_status, TEXT[]) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_article(INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.add_comment(INTEGER, INTEGER, TEXT) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.edit_comment(INTEGER, INTEGER, TEXT) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_comment(INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.add_to_favourites(INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.remove_from_favourites(INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.set_article_rating(INTEGER, INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.remove_article_rating(INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.subscribe_to_user(INTEGER, INTEGER, BOOLEAN) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.unsubscribe_from_user(INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.set_subscription_notices(INTEGER, INTEGER, BOOLEAN) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.report_user(INTEGER, INTEGER, TEXT) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_notification(INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_all_user_notifications(INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_favourite_articles_paginated_filtered(INTEGER, INTEGER, INTEGER, TEXT, TEXT, TEXT) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_notifications_paginated_filtered(INTEGER, INTEGER, INTEGER, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.update_article_status(INTEGER, INTEGER, wonks_ru.article_status) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.create_tag(INTEGER, VARCHAR) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.update_tag(INTEGER, INTEGER, VARCHAR) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_tag(INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.create_category(INTEGER, VARCHAR) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.update_category(INTEGER, INTEGER, VARCHAR) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_category(INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.process_report(INTEGER, INTEGER, wonks_ru.complaint_status) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_reports_paginated_filtered(INTEGER, INTEGER, TEXT, TEXT, TEXT, TIMESTAMPTZ, TIMESTAMPTZ) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.set_user_status(INTEGER, INTEGER, wonks_ru.user_status) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_article_details(TEXT) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_profile(INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.change_user_password(INTEGER, TEXT, TEXT) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.mark_notification_read(INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.mark_all_notifications_read(INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_unread_notification_count(INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_category_list() TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_tag_list() TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_category_by_name(TEXT) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_tag_by_name(TEXT) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.check_user_favourite(INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.check_user_rating(INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.check_user_subscription(INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_by_category(INTEGER, INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_by_tag(INTEGER, INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_by_author(INTEGER, INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_articles_by_status(wonks_ru.article_status, INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_feed(INTEGER, INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_trending_articles(INTERVAL, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_subscriptions(INTEGER, INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_followers(INTEGER, INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_user_comments(INTEGER, INTEGER, INTEGER) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.register_user(VARCHAR, VARCHAR, TEXT) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.authenticate_user(TEXT, TEXT) TO Админ;
-- Высшие права Администратора:
GRANT EXECUTE ON FUNCTION wonks_ru.set_user_role(INTEGER, INTEGER, VARCHAR) TO Админ;
-- set_user_status уже включен в права Модератора
GRANT EXECUTE ON FUNCTION wonks_ru.export_schema_to_jsonb(TEXT) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.import_schema_from_jsonb(JSONB, TEXT, TEXT) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.export_schema_to_json_file(TEXT, TEXT) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.import_schema_from_json_file(TEXT, TEXT, TEXT) TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.get_dashboard_stats() TO Админ;
GRANT EXECUTE ON FUNCTION wonks_ru.delete_user_account(INTEGER, INTEGER) TO Админ;

-- === Демо пользователи ===
CREATE USER admin_user WITH PASSWORD 'admin';
GRANT Админ TO admin_user;

CREATE USER moderator_user WITH PASSWORD 'moderator';
GRANT Модератор TO moderator_user;

CREATE USER standard_user WITH PASSWORD 'user';
GRANT Пользователь TO standard_user;

CREATE USER guest_user WITH PASSWORD 'guest';
GRANT Гость TO guest_user;

ALTER USER admin_user     SET search_path = wonks_ru;
ALTER USER moderator_user SET search_path = wonks_ru;
ALTER USER standard_user  SET search_path = wonks_ru;
ALTER USER guest_user     SET search_path = wonks_ru;

GRANT CONNECT ON DATABASE postgres TO admin_user, moderator_user, standard_user, guest_user;